---
- name: Set ai stack variables
  set_fact:
    stack_name: "ai-stack"
    stack_config: "{{ ai_stack }}"
    stack_services:
      - homeassistant
      - n8n
      - gotify
      - apprise_api
    stack_compose_template: "{{ role_path }}/templates/docker-compose.yml.j2"

- name: Deploy ai stack using common docker-stack role
  include_role:
    name: base-stack
  vars:
    stack_name: "{{ stack_name }}"
    stack_config: "{{ stack_config }}"
    stack_services: "{{ stack_services }}"
    stack_compose_template: "{{ stack_compose_template }}"
