---
- name: Create Docker network for utility stack
  docker_network:
    name: "{{ utility_stack.network_name }}"
    state: present

- name: Stop existing utility stack (if running)
  docker_compose:
    project_src: "{{ utility_stack.base_path }}"
    state: absent
  ignore_errors: yes
  tags: ['never', 'force-restart']

- name: Start utility stack with docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ utility_stack.base_path }}"
    build: never
    state: present
    pull: missing
    remove_orphans: yes
  register: compose_result

- name: Display docker-compose results
  debug:
    var: compose_result.services
  when: cjmpose_result.changed

- name: Ensure all enabled services are running
  docker_container_info:
    name: "{{ item.key }}"
  register: container_info
  loop: "{{ services | dict2items }}"
  when: item.value.enabled | default(false)
  failed_when: 
    - container_info.exists
    - container_info.container.State.Status != "running"

- name: Create systemd service for utility stack
  template:
    src: systemd/utility-stack.service.j2
    dest: /etc/systemd/system/utility-stack.service
    mode: '0644'
  notify:
    - reload systemd
    - enable utility stack service

- name: Start and enable utility stack service
  systemd:
    name: utility-stack
    state: started
    enabled: yes
    daemon_reload: yes
