---
- name: Set media stack-specific variables
  set_fact:
    stack_role_path: "{{ role_path }}"
    
- name: Deploy media stack using common docker-stack role
  include_role:
    name: base-stack
  vars:
    stack_name: "media-stack"
    stack_config: "{{ media_stack }}"
    stack_services: 
      - homeassistant
      - jellyfin
      - jellyseerr
      - sonarr
      - radarr
      - lidarr
      - prowlarr
      - bazarr
      - qbittorrent
      - releasarr
      - suggestarr
      - kavita
      - immich
      - lychee
      - mame
      - your_spotify

    stack_compose_template: "{{ stack_role_path }}/templates/docker-compose.yml.j2"
    stack_systemd_template: "{{ stack_role_path }}/templates/systemd/media-stack.service.j2"
    services: "{{ media_services }}"
