---
- name: Set core stack-specific variables
  set_fact:
    stack_pull_images: false
    stack_verify_health: true
    stack_role_path: "{{ role_path }}"


###

- name: Generate traefik.yml
  template:
    src: traefik.yml.j2
    dest: "{{ core_stack.config_path }}/traefik/traefik.yml"
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
    mode: '0644'
    backup: yes
#  notify: restart core stack
#
- name: Generate config.yml
  template:
    src: config.yml.j2
    dest: "{{ core_stack.config_path }}/traefik/config.yml"
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
    mode: '0644'
    backup: yes
##  notify: restart core stack
#
- name: Create acme.json file with correct permissions
  file:
    path: "{{ core_stack.config_path }}/traefik/acme.json"
    state: touch
    mode: '0600'
    modification_time: preserve
    access_time: preserve

- name: Create acquis.yaml file with correct permissions
  file:
    path: "{{ core_stack.config_path }}/crowdsec/acquis.yaml
"
    state: touch
    mode: '0600'
    modification_time: preserve
    access_time: preserve

####

- name: Deploy core stack using common docker-stack role
  include_role:
    name: base-stack
  vars:
    stack_name: "core-stack"
    stack_config: "{{ core_stack }}"
    stack_services:
      - traefik
      - portainer
      - grafana
      - uptime_kuma
      - filebrowser
      - crowdsec
      - wireshark
    stack_compose_template: "{{ stack_role_path }}/templates/docker-compose.yml.j2"
    stack_systemd_template: "{{ stack_role_path }}/templates/systemd/core-stack.service.j2"
    services: "{{ core_services }}"


