---
proxy_stack_base_path: "/opt/proxy"
proxy_stack:
  base_path: "{{ proxy_stack_base_path }}"
  config_path: "{{ proxy_stack_base_path }}/configs"
  data_path: "{{ proxy_stack_base_path }}/data"

  user_id: "{{ user_id | default('1000')}}"
  group_id: "{{ group_id | default('1000')}}"
  timezone: "{{ timezone | default('Africa/Nairobi')}}"

  network_name: "traefik_net"

  versions:
    traefik: "3.5.3"

# Service configuration
proxy_services:
  traefik:
    enabled: true 
    https: 443
    http: 82
    version: "{{ proxy_stack.versions.traefik | default('latest') }}"
    dashboard:
      enabled: true 
      url: "traefik.{{ domain }}"
      credentials: "{{ vault_traefik_credentials }}"
    insecure_skip_verify: true
    acme:
      email: "{{ vault_traefik_acme_email }}"
      server: "https://acme-v02.api.letsencrypt.org/directory"
    debug: true
    cloudflare: 
      token: "{{ vault_cloudflare_token }}"
    cert_resolver: "cloudflare"
    dns: 
      provider: "cloudflare"
      disable_propagation_check: false
      resolvers: 
        - '1.1.1.1:53'
        - '1.0.0.0:53'
