- name: Get enabled services from configuration
  set_fact:
    stack_services: "{{ services }}"

- name: Display deployment info
  debug:
    msg:
      - "Stack: {{ stack_name }}"
      - "Services to deploy: {{ stack_services | join(', ') }}"
      - "Total services: {{ stack_services | length }}"

- name: Include directory creation tasks
  include_tasks: directories.yml
  tags: ['directories']

- name: Include configuration tasks
  include_tasks: configs.yml
  tags: ['configs']

- name: Include docker-compose deployment
  include_tasks: docker-compose.yml
  tags: ['deploy']

- name: Include verification tasks
  include_tasks: verify.yml
  tags: ['verify']
