---
- name: Wait for services to be ready
  wait_for:
    port: "{{ services[item].port }}"
    host: "127.0.0.1"
    delay: 5
    timeout: 300
    msg: "{{ item }} service did not start within 5 minutes"
  loop: "{{ stack_services }}"
  when: 
    - services[item].enabled | default(true)
    - services[item].port is defined

- name: Check Docker container status
  docker_container_info:
    name: "{{ item }}"
  register: container_status
  loop: "{{ stack_services }}"
  when: services[item].enabled | default(true)

- name: Verify containers are running
  assert:
    that:
      - item.exists
      - item.container.State.Status == "running"
      - item.container.State.Health.Status is undefined or item.container.State.Health.Status == "healthy"
    fail_msg: "Container {{ item.container.Name }} is not running properly"
    success_msg: "Container {{ item.container.Name }} is running and healthy"
  loop: "{{ container_status.results }}"
  when: 
    - item.item is defined
    - services[item.item].enabled | default(false)

- name: Verify data directory permissions
  stat:
    path: "{{ stack_config.data_path }}/{{ item }}"
  register: data_dir_stats
  loop: "{{ stack_services }}"
  when: services[item].enabled | default(true)

- name: Check data directory ownership
  assert:
    that:
      - data_dir_stats.results[index].stat.uid == stack_config.user_id | int
      - data_dir_stats.results[index].stat.gid == stack_config.group_id | int
    fail_msg: "Data directory {{ item }} has incorrect ownership"
  loop: "{{ stack_services }}"
  loop_control:
    index_var: index
  when: 
    - services[item].enabled | default(true)
    - data_dir_stats.results[index].stat.exists

- name: Check systemd service status
  systemd:
    name: "{{ stack_name }}"
    state: started
  register: systemd_status

- name: Verify systemd service is enabled
  command: systemctl is-enabled {{ stack_name }}
  register: systemd_enabled
  changed_when: false
  failed_when: systemd_enabled.stdout != "enabled"
