---
- name: Set automation stack-specific variables
  set_fact:
    stack_role_path: "{{ role_path }}"
    
- name: Deploy automation stack using common docker-stack role
  include_role:
    name: base-stack
  vars:
    stack_name: "automation-stack"
    stack_config: "{{ automation_stack }}"
    stack_services: 
      - homeassistant
      - n8n
      - gotify
      - apprise_api
    stack_compose_template: "{{ stack_role_path }}/templates/docker-compose.yml.j2"
    stack_systemd_template: "{{ stack_role_path }}/templates/systemd/automation-stack.service.j2"
    services: "{{ automation_services }}"

