---
- name: Deploy Media stack
  hosts: "{{ target_hosts | default('media_servers') }}"
  become: yes
  gather_facts: yes
  serial: " {{ deploy_serial | default(1) }}"

  vars_files:
    - ../vars/versions.yml

  vars:
    stack_name: "media-stack"
    services: "{{ media_services }}"
    stack: "{{ media_stack }}"
 
  roles:
    - role: pre-checks
      tags: ["media-pre-checks"]
    - role: dynamic-stack
      tags: ['media']
