---
- name: Deploy productivity stack
  hosts: "{{ target_hosts | default('productivity_servers') }}"
  become: yes
  gather_facts: yes
  serial: " {{ deploy_serial | default(1) }}"

  pre_tasks:
    - name: Display deployment plan
      debug:
        msg:
          - "Deploying productivity stack to: {{ inventory_hostname }}"
          - "Services to deploy:"
          - "   - Nextcloud: {{ productivity_services.nextcloud.enabled | default(false) }}"
          - "   - Gitea: {{ productivity_services.gitea.enabled | default(false) }}"
          - "   - Code server: {{ productivity_services.code_server.enabled | default(false) }}"
          - "   - Penpot: {{ productivity_services.penpot.enabled | default(false) }}"
          - "   - Quant UX: {{ productivity_services.quant_ux.enabled | default(false) }}"
          - "   - Grocy: {{ productivity_services.grocy.enabled | default(false) }}"
          - "   - Hortusfox: {{ productivity_services.hortusfox.enabled | default(false) }}"
      tags: always

  roles:
    - role: pre-checks
      tags: ["productivity-pre-checks"]
    - role: productivity-stack
      tags: ['productivity']
#      
#  post_tasks:
#    - name: Confirming services are running
#      wait_for:
#        port: "{{ item.port }}"
#        host: "{{ ansible_host }}"
#        delay: 10
#        timeout: 300
#      loop:
#        - { service: "nextcloud", port: "{{ productivity_stack.services.nextcloud.port }}" }
#        - { service: "gitea", port: "{{ productivity_stack.services.gitea.port }}" }
#        - { service: "code_server", port: "{{ productivity_stack.services.code_server.port }}" }
#        - { service: "penpot", port: "{{ productivity_stack.services.penpot.port }}" }
#        - { service: "quant_ux", port: "{{ productivity_stack.services.quant_ux.port }}" }
#        - { service: "grocy", port: "{{ productivity_stack.services.grocy.port }}" }
#        - { service: "hortusfox", port: "{{ productivity_stack.services.hortusfox.port }}" }
#      when: services[item.service].enabled | default(true)
#      
#    - name: Display access information
#      debug:
#        msg:
#          - "Productivity services have been deployed successfully!"
#          - ""
#          - "Service URLs:"
#      tags: always
