#---
#- name: Deploy Proxy stack
#  hosts: "{{ target_hosts | default('proxy_servers') }}"
#  become: yes
#  gather_facts: yes
#  serial: " {{ deploy_serial | default(1) }}"
#
#  vars_files:
#    - ../vars/versions.yml
#    - ../vars/traefik.yml
#
#  pre_tasks:
#    - name: Display deployment plan
#      debug:
#        msg:
#          - "Deploying proxy stack to: {{ inventory_hostname }}"
#          - "Services to deploy:"
#          - "   - Traefik: {{ services.traefik.enabled | default(true) }}"
#      tags: always
#
#  roles:
#    - role: proxy-stack
#      tags: ['proxy']
#      
#  post_tasks:
#    - name: Confirming services are running
#      wait_for:
#        port: "{{ item.port }}"
#        host: "{{ ansible_host }}"
#        delay: 10
#        timeout: 300
#      loop:
#        - { service: "traefik", port: "{{ proxy_stack.services.traefik.https }}" }
#      when: services[item.service].enabled | default(true)
#      
#    - name: Display access information
#      debug:
#        msg:
#          - "Traefik has been deployed successfully!"
#          - ""
#          - "Service URLs:"
#          - "  Domain:              https://{{ domain }}"
#          - "  Traefik:             https://{{ dashboard.host }}"
#          - "  Traefik dashboard:   https://{{ dashboard.host }}/dashboard"
#      tags: always
