---
- name: Deploy core systems stack
  hosts: "{{ target_host | default('core_servers') }}"
  become: yes
  gather_facts: yes
  serial: "{{ deploy_serial | default(1) }}"

  vars_files:
    - ../vars/versions.yml

  pre_tasks:
    - name: Display deployment plan
      debug:
        msg:
          - "Deploying core system stack to: {{ inventory_hostname }}"
          - "Services to deploy:"
          - " - Traefik: {{ services.traefik.enabled | default(true) }}"
          - " - Portainer: {{ services.portainer.enabled | default(true) }}"
          - " - Grafana: {{ services.grafana.enabled | default(true) }}"
          - " - Uptime kuma: {{ services.uptime_kuma.enabled | default(true) }}"
          - " - Filebrowser: {{ services.filebrowser.enabled | default(true) }}"
          - " - Crowdsec: {{ services.crowdsec.enabled | default(true) }}"
          - " - Wireshark: {{ services.wireshark.enabled | default(true) }}"
          - " - Adguard hoe: {{ services.adguard_home.enabled | default(true) }}"
      tags: always

  roles:
    - role: pre-checks
      tags: ["core-systems-pre-check"]
    - role: core-stack
      tags: ['core']

#  post_tasks:
#    - name: Confirming services are running
#      wait_for:
#        port: "{{ item.port }}"
#        host: "{{ ansible_host }}"
#        delay: 10
#        timeout: 300
#      loop:
#        - { service: "portainer", port: "{{ services.portainer.port }}"}
#        - { service: "filebrowser", port: "{{ services.filebrowser.port }}"}
#        - { service: "uptime_kuma", port: "{{ services.uptime_kuma.port }}"}
#        - { service: "grafana", port: "{{ services.grafana.port }}"}
#      when: services[item.service].enabled | default(true)
#      
#    - name: Display access information
#      debug:
#        msg:
#          - "core_system stack deployed successfully"
#          - ""
#          - "Service URLs:"
#          - "  Portainer:    http://{{ ansible_host }}:{{ services.portainer.port }}"
#          - "  Filebrowser:    http://{{ ansible_host }}:{{ services.filebrowser.port }}"
#          - "  Uptime-kuma:    http://{{ ansible_host }}:{{ services.uptime_kuma.port }}"
#      tags: always
