---
- name: Deploy stack with environment
  hosts: "{{ target_hosts }}"
  become: yes
  gather_facts: yes
  vars_files:
    - ../vars/versions.yml
    - "../vars/stacks/{{ stack_type }}/vault.yml"
    - "../vars/stacks/{{ stack_type }}/base.yml"
#    - "../vars/stacks/{{ stack_type }}/{{ environment | default('production') }}.yml"
  vars:
    stack_name: "{{ stack_type }}-stack"
    services: "{{ lookup('vars', stack_type + '_services') }}"
    stack: "{{ lookup('vars', stack_type + '_stack') }}"

  roles:
    - role: pre-checks
    - role: dynamic-stack
