---
- name: Deploy core systems stack
  hosts: "{{ target_host | default('core_servers') }}"
  become: yes
  gather_facts: yes
  serial: "{{ deploy_serial | default(1) }}"

  vars_files:
    - ../vars/versions.yml

  vars:
    stack_name: "core-stack"
    services: "{{ core_services }}"
    stack: "{{ core_stack }}"
 
  roles:
    - role: pre-checks
      tags: ["core-pre-checks"]
    - role: dynamic-stack
      tags: ['core']
