---
- name: Deploy fincance stack
  hosts: "{{ target_hosts | default('finance_servers') }}"
  become: yes
  gather_facts: yes
  serial: " {{ deploy_serial | default(1) }}"

  pre_tasks:
    - name: Display deployment plan
      debug:
        msg:
          - "Deploying finance stack to: {{ inventory_hostname }}"
          - "Services to deploy:"
          - "   - Akauntant: {{ finance_services.akauntant.enabled | default(true) }}"
      tags: always

  roles:
    - role: pre-checks
      tags: ["finance-pre-check"]
    - role: finance-stack
      tags: ['fincance']
