# Host users configuration
user: "{{ ansible_user }}"
users_to_create:
  - name: "emmental"
    group: "emmental"
    hosts:
      - "all"
    ssh_key_file: "~/.ssh/id_rsa.pub"

# Docker configuration
docker_users:
  - "{{ ansible_user }}"

user_id: 1000
group_id: 987

timezone: "Africa/Nairobi"

custom_dns: "100.80.220.126"

default_domain: "example.com"
default_subdomain: "traefik"
domain_final: "{{ my_domain | default(default_domain) }}"
subdomain_final: "{{ subdomain | default(default_subdomain) }}"
domain: "{{ (subdomain_final | default('') | length > 0) | ternary(subdomain_final ~ '.', '') }}{{ domain_final }}"

netbird_setup_key: "{{ vault_netbird_setup_key }}"
