---
# core_systems stack configuration
core_systems_stack_base_path: "/opt/core-stack"
core_stack:
  # Paths
  base_path: "{{ core_systems_stack_base_path }}"
  config_path: "{{ core_systems_stack_base_path }}/configs"
  data_path: "{{ core_systems_stack_base_path }}/data"

  user_id: "{{ user_id | default('1000')}}"
  group_id: "{{ group_id | default('1000')}}"
  timezone: "{{ timezone | default('Africa/Nairobi')}}"
  
  # Network
  network_name: "core_systems-net"
  
  # Domain configuration
  domain: "{{ core_systems_domain | default('localhost') }}"
  enable_ssl: false
 
  # Container versions (can be overridden per environment)
  versions:
    traefik: "3.5.3"
    portainer: "lts"
    grafana: "main"
    uptime_kuma: "1"
    filebrowser: "v2-s6"
    crowdsec: "latest"
    wireshark: "latest"
    adguard_home: "latest"

# Service configuration
core_services:
  adguard_home:
    enabled: true
    port: 80
    version: "{{ core_stack.versions.adguard_home | default('latest') }}"
  traefik:
    enabled: false
    https: 443
    http: 81
    version: "{{ core_stack.versions.traefik | default('latest') }}"
  portainer:
    enabled: false
    port: 9443
    version: "{{ core_stack.versions.portainer | default('lts') }}"
  grafana:
    enabled: false
    port: 3000
    version: "{{ core_stack.versions.grafana | default('main') }}"
  uptime_kuma:
    enabled: false
    port: 3001
    version: "{{ core_stack.versions.uptime_kuma | default('1') }}"
  filebrowser:
    enabled: false
    port: 8081
    version: "{{ core_stack.versions.filebrowser | default('latest') }}"
  crowdsec:
    enabled: false
    port: 8083
    version: "{{ core_stack.versions.crowdsec | default('latest') }}"
  wireshark:
    enabled: false
    port: 3001
    version: "{{ core_stack.versions.wireshark | default('latest') }}"
  adguard_home:
    enabled: false
    port: 80
    version: "{{ core_stack.versions.adguard_home | default('latest') }}"
  
# Cloudflare credentials
cloudflare_api_token: "{{ cloudflare_token }}"

# Traefik dashboard credentials (htpasswd format)
traefik_dashboard_credentials: "{{ dashboard.credentials }}"
traefik_dashboard_host: "{{ dashboard.host }}"

# Traefik configuration
traefik_acme_email: "{{ acme_email }}"
traefik_debug: false

# Auto-generate routes from this list
traefik_routes:
  - name: proxmox
    host: proxmox
    service: proxmox
    
  - name: portainer
    host: portainer
    service: portainer

# Define backend services
traefik_services:
  - name: proxmox
    servers:
      - url: "https://192.168.0.3:8006"
    pass_host_header: false
