---
# core_systems stack configuration
core_systems_stack_base_path: "/opt/core-stack"
core_stack:
  # Paths
  base_path: "{{ core_systems_stack_base_path }}"
  config_path: "{{ core_systems_stack_base_path }}/configs"
  data_path: "{{ core_systems_stack_base_path }}/data"

  user_id: "{{ user_id | default('1000')}}"
  group_id: "{{ group_id | default('1000')}}"
  timezone: "{{ timezone | default('Africa/Nairobi')}}"
  
  # Network
  network_name: "core_systems-net"
  
  # Domain configuration
  domain: "{{ core_systems_domain | default('localhost') }}"
  enable_ssl: false
 
  # Container versions (can be overridden per environment)
  versions:
    grafana: "main"
    uptime_kuma: "1"
    filebrowser: "v2-s6"
    crowdsec: "latest"
    wireshark: "latest"
    adguard_home: "latest"

# Service configuration
core_services:
  adguard_home:
    enabled: true
    http: 81
    https: 8443
    version: "{{ core_stack.versions.adguard_home | default('latest') }}"

