---
# productivity stack configuration
productivity_stack_base_path: "/opt/productivity-stack"
productivity_stack:
  # Paths
  base_path: "{{ productivity_stack_base_path }}"
  config_path: "{{ productivity_stack_base_path }}/configs"
  data_path: "{{ productivity_stack_base_path }}/data"

  user_id: "{{ user_id | default('1000')}}"
  group_id: "{{ group_id | default('1000')}}"
  timezone: "{{ timezone | default('Africa/Nairobi')}}"

  # Network
  network_name: "productivity-net"
  
  # Domain configuration
  domain: "{{ productivity_domain | default('localhost') }}"
  enable_ssl: false
 
  # Container versions (can be overridden per environment)
  versions:
    nextcloud: "stable"
    gitea: "1.24.6"
    code_server: "latest"
    grocy: "latest"
    penpot: ""
    quant_ux: ""
    hortusfox: ""

# Service configuration
productivity_services:
  nextcloud:
    enabled: false
    port: 7443
    version: "{{ productivity_stack.versions.nextcloud | default('stable') }}"
  gitea:
    enabled: true
    port1: 8088
    port2: 2221
    version: "{{ productivity_stack.versions.gitea | default('1.24.6') }}"
  code_server:
    enabled: true
    port: 9444
    version: "{{ productivity_stack.versions.code_server | default('latest') }}"
  grocy:
    enabled: true
    port: 89
    version: "{{ productivity_stack.versions.grocy | default('latest') }}"
  hortusfox:
    enabled: false
    port: 9443 
    version: "{{ productivity_stack.versions.hortusfox | default('lts') }}"

