---
utility_systems_stack_base_path: "/opt/utility-stack"
utility_stack:
  # Paths
  base_path: "{{ utility_systems_stack_base_path }}"
  config_path: "{{ utility_systems_stack_base_path }}/configs"
  data_path: "{{ utility_systems_stack_base_path }}/data"
  media_path: "/mnt/media"

  user_id: "{{ user_id | default('1000')}}"
  group_id: "{{ group_id | default('1000')}}"
  timezone: "{{ timezone | default('Africa/Nairobi')}}"
  
  stack_domain: "{{ domain }}"
  
  # Network
  network_configs:
    utility_net:
      name: utility_net
      driver: bridge
    traefik_net:
      name: traefik_net
      external: true
  
  # Container versions (can be overridden per environment)
  versions:
    portainer: "2.33.0"
    grafana: "main"
    uptime_kuma: "1"
    filebrowser: "v2-s6"
    filestash: "latest"
    crowdsec: "latjst"
    wireshark: "latest"
    adguard_home: "latest"
    vaultwarden: "latest"
    filestash: "latest"
    glance: "latest"
    cadvisor: "latest"
    node_exporter: "latest"
    netbird: "latest"
    homeassistant: "stable"
    n8n: 
      app: "1.120.3"
      postgres: "17-alpine"


# Service configuration
utility_services:
  cadvisor:
    enabled: true
    port: 8081
    version: "{{ utiltiy_stack.versions.cadvisor | default('latest') }}"
  node_exporter:
    enabled: true
    port: 9100
    version: "{{ utility_stack.versions.node_exporter | default('latest') }}"
  netbird:
    enabled: true 
    version: "{{ utility_stack.versions.netbird | default('latest') }}"
    hostname: hive
    setup_key: "{{ netbird_setup_key }}"
  portainer:
    enabled: false
    port: 9443
    version: "{{ utility_stack.versions.portainer | default('lts') }}"
    networks:
      - traefik_net
    traefik:
      enabled: true 
      host: "portainer"
      domain: "{{ utility_stack.stack_domain }}"
  uptime_kuma:
    enabled: true
    port: 3001
    version: "{{ utility_stack.versions.uptime_kuma | default('1') }}"
    dnss:
      - "{{ custom_dns }}"
    networks:
      - traefik_net
    traefik:
      enabled: true 
      host: "uptime"
      domain: "{{ utility_stack.stack_domain }}"
  vaultwarden:
    enabled: true 
    port: 5554
    version: "{{ utility_stack.versions.vaultwarden | default('latest') }}"
    networks:
      - traefik_net
    traefik:
      enabled: true 
      host: "vault"
      domain: "{{ utility_stack.stack_domain }}"
  filestash:
    enabled: true
    port: 8334
    version: "{{ utility_stack.versions.filestash | default('latest') }}"
    networks:
      - traefik_net
    traefik:
      enabled: false 
      host: "filestash"
      domain: "{{ utility_stack.stack_domain }}"
  gotify:
    enabled: true 
    port: 411
    version: "{{ utility_stack.versions.gotify | default('latest') }}"
    dnss:
      - "{{ custom_dns }}"
    networks:
      - traefik_net
    traefik:
      enabled: true
      host: "gotify"
      domain: "{{ domain }}"
  homeassistant:
    enabled: false
    port: 8123
    version: "{{ utility_stack.versions.homeassistant | default('stable') }}"
    networks:
      - traefik_net
    traefik:
      enabled: true 
      host: "home"
      domain: "{{ domain }}"
  glance:
    enabled: false 
    port: 8082
    version: "{{ utility_stack.versions.glance | default('latest') }}"
    networks:
      - traefik_net
    traefik:
      enabled: false 
      host: "view"
      domain: "{{ utility_stack.stack_domain }}"
  n8n:     
    enabled: true 
    port: 5678
    encryption_key: "{{ vault_n8n_encryption_key }}"
    version: "{{ utility_stack.versions.n8n.app | default('latest') }}"
    db_version: "{{ utility_stack.versions.n8n.postgres | default('latest') }}"
    db:
      user: "carlos"
      password: "{{ vault_n8n_db_password }}"
      user_non_root: "barb"
      password_non_root: "{{ vault_n8n_db_password_non_root }}"
      name: "my_n8n"
    networks:
      - traefik_net
    traefik:
      enabled: true
      host: "n8n"
      domain: "{{ domain }}"
  grist:
    enabled: true 
    port: 8484
    version: "{{ utility_stack.versions.gotify | default('latest') }}"
    secret: "{{ vault_grist_secret }}"
    email: "ops@brianphiri.com"
    dnss:
      - "{{ custom_dns }}"
    networks:
      - traefik_net
    traefik:
      enabled: true
      host: "sheets"
      domain: "{{ domain }}"


